-- Usage analytics: module views and document generation
ALTER TABLE public.audit_logs
  DROP CONSTRAINT IF EXISTS audit_logs_action_type_check;

ALTER TABLE public.audit_logs
  ADD CONSTRAINT audit_logs_action_type_check
  CHECK (action_type IN (
    'CREATE_USER', 'UPDATE_USER', 'BLOCK_USER', 'UNBLOCK_USER', 'UPDATE_PERMISSION',
    'CREATE_MODULE', 'UPDATE_MODULE', 'DELETE_MODULE',
    'CREATE_DYNAMIC_TABLE', 'UPDATE_DYNAMIC_TABLE', 'DELETE_DYNAMIC_TABLE', 'UPDATE_TABLE_COLUMNS',
    'CREATE_CHART', 'UPDATE_CHART', 'DELETE_CHART',
    'IMPORT_EXCEL', 'UPDATE_PASSWORD', 'UPDATE_DATA_ACCESS',
    'RESTORE', 'SYSTEM',
    'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGIN_BLOCKED_BY_RATE_LIMIT', 'LOGIN_BLOCKED_IP',
    'FILE_UPLOAD', 'FILE_DOWNLOAD', 'FILE_DELETE', 'FILE_MOVE', 'FILE_SHARE', 'BULK_FILE_MOVE',
    'FOLDER_CREATE', 'FOLDER_DELETE',
    'IMPERSONATION_START', 'IMPERSONATION_END',
    'MODULE_VIEW', 'DOCUMENT_GENERATE'
  ));
